import { type NextPage } from "next";
import Head from "next/head";

// react hooks
import { useState } from "react";

// local components
import { SearchInput } from "~/components/Test";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SearchInput />
      </main>
    </>
  );
};

export default Home;
